MainPage:


<MainPage>:
	orientation: 'vertical'


	BoxLayout:
		size_hint: 1, .15
		Button:
			size_hint: .20, 1
			text: 'N.G.'

		Label:
			text: 'yeet'

		Button:
			size_hint: .20, 1
			text: 'info'


	ScrollView:
		LabelStack:

		
		
			


	StackNumber:
		size_hint: 1, .55


	AnchorLayout:
		size_hint: 1, .18
		Button:
			size_hint: .5, 1
			text: 'End Game?'
			on_press: root.end_game()
		
		